package com.privacity.cliente.singleton.sharedpreferences;

public enum SharedPreferencesEnum {
    WS_SERVER_PROTOCOL  , WS_SERVER_URL,  WS_SERVER_PORT,
    APP_SERVER_PROTOCOL ,  APP_SERVER_URL,  APP_SERVER_PORT

    ,DEVELOPER_MODE,USER, PASSWORD,LANGUAGE, BUTTON_SETUP,TEXT_SIZE_MESSAGE__SIZE,TEXT_SIZE_MESSAGE__VIEW_STATUS,RECONNECT_STATE
    ,RECONNECT_LOG_STATE,TIME_MESSAGE
}
